### ISSUE TITLE
Add a TAG for Players without Prime Status

### ISSUE THREAD

**Issue by crashzk** [Summer-16/CSGO-NonPrimePlayerKicker#2]
Add a TAG for Players without Prime Status

That is, even if he manages to enter because of `BypassPremiumCheck` it would be marked with a TAG `[NOPRIME]` just so we can identify.

**Comment by Summer-16** [comment]
Added, Check the latest release and do provide the feedback if you get any errors.

**Comment by crashzk** [comment]
Thank you, I will be testing and notifying you of any errors.

**Comment by crashzk** [comment]
@Summer-16 TAG worked, showing on players that don't have Prime.

However I found a BUG, ​​even though the player does not have the Prime Status, and even privileges within the server it cannot connect. I found out because now it shows the TAG in it `[NOM-PRIME]`.

I did the test myself, created a new CSGO account, I was unable to log in, the server kicked me and shows the reason message.

However players who have already passed Level 2, but still have no Prime Status for what I saw can still enter.

**Comment by crashzk** [comment]
Here are some screenshots showing the BUG.
![image](https://user-images.githubusercontent.com/32937653/77357815-87570280-6d27-11ea-8d5b-0a398c79db9c.png)

![image](https://user-images.githubusercontent.com/32937653/77357856-a05fb380-6d27-11ea-92f2-716a32436eea.png)

Shouldn't they be kicked? Since you have no Prime Status and no privileges on the server.

**Comment by Summer-16** [comment]
@crashzk Yes the players who don't have a prime account but has crossed CSGO level 2 can connect inside the server, as I mentioned in readme too, if you want to increase the level, for now, you can change the 2 in 2nd if condition to any prefered level or can wait for next release I will add a cvar for that.

**Comment by crashzk** [comment]
> Yes the players who don't have a prime account but has crossed CSGO level 2 can connect inside the server, as I mentioned in readme too, if you want to increase the level, for now, you can change the 2 in 2nd if condition to any prefered level or can wait for next release I will add a cvar for that.

Now I understood, sorry, lack of attention from me at the time of reading.

So apparently everything is fine, thanks!
