### ISSUE TITLE
Player even having the requested level cannot connect

### ISSUE THREAD

**Issue by crashzk** [Summer-16/CSGO-NonPrimePlayerKicker#4]
https://github.com/Summer-16/CSGO-NonPrimePlayerKicker/blob/d66b4830300820932e4883f9cd6a1201d605fa3e/NonPrimeKicker.sp#L51

I believe this line should look like this:
```
 } else if (playerlevel => minimumLevel) { 
```
Because in the current configuration, CVAR comes with the standard that the player must have at least level 2, but the player can only enter if it is level 3.

That is, for the player to connect we have to configure the CVAR `sm_npmk_kicklevel` with `1`, `sm_npmk_kicklevel "1"`, then players with level 2 can connect.

**Comment by Summer-16** [comment]
well, u can still make it 1 if you want level 2 guy to pass on, Also updated the Readme.
I will update the confusing cfg variable in the next commit.
