### ISSUE TITLE
Allow the entry of players who have the account for x days

### ISSUE THREAD

**Issue by crashzk** [Summer-16/CSGO-NonPrimePlayerKicker#5]
Allow the entry of players who have the account for x days.

### HOW IT WORKS
It would have a CVAR that would control how many days the player's steam needs to be created in order to enter.

Example, `sm_npmk_minimum_days "15"`, then only players with 15 days of steam account would be able to enter.

### IMPLEMENTATION
CVAR `sm_npmk_kicklevel` would be interesting if you can have an option to disable it, the user would configure it with `0` then there would be no verification, skip this part. Currently I set it to zero, but it still checks.

This implementation would also be good for the suggestion in CVAR `sm_npmk_minimum_days`.

**Comment by Summer-16** [comment]
I don't think that steam profile data is available if any user has a private profile, I will check what are the possibilities.

**Comment by crashzk** [comment]
Any news? Do you think it will be possible to implement?

On the question of the private profile, an idea would be to expel the player if he does not have the public profile.

Or even verification steps, example:
- Checks first if the player has Prime Status;
- Checks if the player has the CSGO Level together with CVAR `sm_npmk_minimum_days`;

That is, if his account is less than X days old, even with the required CSGO Level, he is unable to connect to the server.

Now if he has X days and the CSGO Level he can enter.

_**OBS: Of course, the immunity CVAR still continues, if the player has immunity it does not pass the checks.**_

**Comment by Summer-16** [comment]
I will update as soon as I get time to look into this, lately, I been busy with other stuff.

**Comment by crashzk** [comment]
I've been checking this feature request, I believe that instead of checking how many days the account has. It would be interesting to check the playing time that the player has. 

Example, a cvar that controls the time limit on the CSGO that the player must have to enter the server, that is, if I configure that he must have at least 50 hours of CSGO played to enter the server.

**Comment by Summer-16** [comment]
I have this feature request for this plugin on my list, I know I was not able to update this plugin as i was busy with VMPanel but i will get back to it really soon after completing the V1.2 for VMPanel.

**Comment by crashzk** [comment]
Hello, news about this update?

**Comment by Summer-16** [comment]
Replaced CSGO level check with CSGO Play hours check as levels get reset after getting a medal.
Plugin updated this should resolve the issue.

**Comment by crashzk** [comment]
Implementing hours is a good thing, but I liked the option of checking the CSGO Level, would it be possible to add it again?

Make it work like the time checking option, if you want to use it, leave it activated and configure what minimum level the player has to have in CSGO to enter.

I believe that a good solution to the problem of resetting the CSGO level when it reaches level 41, would be to implement a database to save the players that are all right to connect to the server, saving it in this database would not check it anymore.

**Comment by Summer-16** [comment]
Now you can choose between level or hours, and about the database integration i have no plans of adding database funtionality in this plugin as my aim was to keep it light from the beginning.
If you really looking for a database based solution the look into this  https://forums.alliedmods.net/showthread.php?t=323407
