### ISSUE TITLE
Doubt with the cvar sm_npmk_kicklevel

### ISSUE THREAD

**Issue by crashzk** [Summer-16/CSGO-NonPrimePlayerKicker#6]
How would I disable this feature?

I tried to leave it like this `sm_npmk_kicklevel "0"` but apparently there are players without Status Prime entering yet.

**Comment by Summer-16** [comment]
You wanna disable it in what way
- So that it will only allow the players with a licence 
- or anyone can get in

**Comment by crashzk** [comment]
> You wanna disable it in what way
> 
> * So that it will only allow the players with a licence

For only players with Status Prime to enter, he will not check his level, that is, no matter what level he is in, if he does not have Status Prime, license, he cannot enter.

**Comment by Summer-16** [comment]
ok now I understand, for that, I will have to add a new cvar. But u understand disabling level check will also restrict players who got prime by reaching level 21 because they became prime but still steam didn't give them the licence , only players who paid for the game has a licence.

**Comment by crashzk** [comment]
Perfect I look forward to this change.

About your question, I understand too. In case I requested this change due to a problem I have been facing, currently the player has to be Prime or have Level 3 in CSGO to get in, so far so good, it works.

However there are players with hackers who enter due to the level and only enter to use hackers.

So I thought about raising, I left Level 21 so they can enter without having Prime Status. AI enters the problem, players reach Level 21 enter and everything, but if they reset his level playing competitive they lose access to the server. I believe that the best solution would be to create a database in this case, the player was able to access the server because he already has the necessary Level or because the Prime Status is registered in the database, even if he resets if the CSGO level he does not pass the verification again, since that his steam is saved in the database.

Did you understand more or less? Sorry for my english, I use google translator.

**Comment by Summer-16** [comment]
I perfectly understand. I will try to release an update as soon as possible. As currently, my hands are full with office work and some other personal projects.

**Comment by crashzk** [comment]
I understand, I'll be waiting, thanks for now.

**Comment by crashzk** [comment]
Doubt, from what I said I would have to create a cvar to control this feature, that is, if I want to disable / activate this kicking option because of the player's level I would have to configure it in another cvar.

Wouldn't it be possible to implement in the cvar `sm_npmk_kicklevel` that you already have? That is, if users want to disable this feature, set it to zero, so `sm_npmk_kicklevel "0"`.

Wouldn't it be better in the case? Or would you need a major modification to the plugin's source code?

Sorry to bother you with that, I really liked this plugin, simple and effective.

**Comment by Summer-16** [comment]
I understand brother, As I will be locking the v1.6 of vmpanel this week I have decide to wok on this plugin in the weekend so you should see some new updated by this weekend

**Comment by Summer-16** [comment]
Resolved

**Comment by crashzk** [comment]
Thank you, I will be testing, and anything will return.

For now just one error, in the Readme, the version is wrong there, there are two 1.3.1.

**Comment by Summer-16** [comment]
maybe a typo,  fetch the latest code from repo. I will update it in a release soon.
